name: Python and Docker CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run Linting Job
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
          
      - name: Setting Up Python
        uses: actions/setup-python@v5
        
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint With ruff
        run: |
          ruff check .
          ruff format --check .
          
  build:
    runs-on: ubuntu-latest
    name: Build Dockerfile
    steps: 
      - name: Build
        run: |
          docker build -t quotes-api ./Dockerfile
          
      - name: Compile
        run: |
          docker run -d --name proof-of-docker quotes-api

      - name: Check for container
        run: |
          container_name = "proof-of-docker"
          if $(docker inspect -f "{{.state.status}}" "$container_name" | grep -q "running"; then
            echo "The container '$container_name' is running."
          else:
            echo "The conatiner '$container_name' is not running."
            exit 1
          fi
          
      - name: Kill the container
        run: |
          docker kill proof-of-docker



