name: Python and Docker CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run Linting Job
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v4
          
      - name: Setting Up Python
        uses: actions/setup-python@v5
        
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint With ruff
        run: |
          ruff check .
          ruff format --check .
          
  build:
    runs-on: ubuntu-latest
    name: Build Dockerfile
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Export Docker Image
        uses: docker/build-push-action@v6
        with:
          tags: quotes-api
          outputs: |
            type=tar,dest=${{runner.temp}}/quotes-api.tar
            type=docker

      - name: Start the container
        run: |
          docker run -d --rm --name quotes-api quotes-api

      - name: Smoke-Check
        uses: stringbean/docker-healthcheck-action@v1
        with:
          container: quotes-api
          wait-time: 30
          require-healthy: true
      
      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: quotes-api
          path: ${{runner.temp}}/quotes-api.tar

      - name: Stop the Container
        if: always()
        run: docker stop quotes-api
          
  scan:
    runs-on: ubuntu-latest
    name: Docker vuln check
    needs: build
    steps:
      - name: Download Image
        uses: actions/download-artifact@v4
        with:
          name: quotes-api
          path: . 
    
      - name: Load Image
        run: |
          docker load --input quotes-api.tar

      - name: Aqua Security Trivy
  # You may pin to the exact commit or the version.
  # uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: 'quotes-api'
          severity: 'HIGH,CRITICAL'
          format: 'table'                




