name: Python and Docker CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run Linting Job
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v4
          
      - name: Setting Up Python
        uses: actions/setup-python@v5
        
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint With ruff
        run: |
          ruff check .
          ruff format --check .
          
  build:
    runs-on: ubuntu-latest
    name: Build Dockerfile
    steps: 
      - name: Checkout Repository
        uses: action/checkout@v4

      - name: Build and Export Image
        uses: docker/build-push-actions@v6
        with:
          tags: quotes-api:latest
          outputs: type=docker,dest=${{runner.temp}}/quotes-api.tar

      - name: Start the container
        run: |
          docker run -d --rm quotes-api

      - name: Smoke-Check
        uses: stringbean/docker-healthcheck-action@v1
        with:
          container: quotes-api
          wait-time: 30
          require-healthy: true

      - name: Upload Image
        uses: actions/upload-artifacts
        with:
          name: quotes-api
          path: ${{runner.temp}}/quotes-api.tar
          
  scan:
    runs-on: ubuntu-latest
    name: Docker vuln check
    




