name: Python and Docker CI

on:
  push:
    branches: ["main"]
  pull:
    branches: ["main"]

jobs:
  precheck:
    runs-on: ubuntu-latest
    name: Stabalization Of Environment 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Setting Up Python
        uses: actions/setup-python@v5
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  lint:
    runs-on: ubuntu-latest
    name: Run Linting Job
    steps:
      - name: Lint With ruff
        run: |
          ruff check .
          ruff format --check .
  build:
    runs-on: ubuntu-latest
    name: Build Dockerfile
    steps: 
      - name: Compile
        run: |
          docker run -d --name proof-of-docker quotes-api
      - name: Verify Docker Action
        uses: christopher-dG/verify-docker-action@v1.0.0
        with:
    # Docker image to verify (e.g. foo/bar:1.2.3)
          image: quotes-api
    # Expected image digest (e.g. sha256:abcdef)
          digest: 2c938e882f87b593486f913fbbc7ba2949e78f9b033bdc2504dbc44f711184f6
          
      - name: Kill the container
        run: |
          docker kill proof-of-docker



