name: Python and Docker CI

permissions:
  contents: read
  packages: write

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run Linting Job
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v4
          
      - name: Setting Up Python
        uses: actions/setup-python@v5
        
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint With ruff
        run: |
          ruff check .
          ruff format --check .
          
  build:
    runs-on: ubuntu-latest
    name: Build Dockerfile
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Export Docker Image
        uses: docker/build-push-action@v6
        with:
          tags: quotes-api

      - name: Start the container
        run: |
          docker run -d --name quotes-api quotes-api

      - name: Smoke-Check
        uses: stringbean/docker-healthcheck-action@v1
        with:
          container: quotes-api
          wait-time: 30
          require-healthy: true
      
      - name: Stop the Container
        if: always()
        run: docker stop quotes-api
          
  scan:
    runs-on: ubuntu-latest
    name: Docker vuln check
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Build and Export Docker Image
        uses: docker/build-push-action@v6
        with:
          tags: quotes-api

      - name: Aqua Security Trivy
  # You may pin to the exact commit or the version.
  # uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: 'quotes-api'
          severity: 'HIGH,CRITICAL'
          format: 'table'                

  publish:
    runs-on: ubuntu-latest
    needs: scan
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to GHCR.io
        uses: docker/login-action
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Extract Metadata For Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          image: ghcr.io/${{github.repository}}
          tags: |
            type=sha
            type=raw,value=latest,enable=${{github.refs}}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}

